-- Find total customers by state
SELECT
	state,
	COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY state
ORDER BY total_customers DESC;

-- Find total customers by city
SELECT
	city,
	COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY city
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
	category_name,
	COUNT(product_key) total_products
FROM gold.dim_products
GROUP BY category_name
ORDER BY total_products DESC;

-- What is average price in each category?
SELECT
	p.category_name,
	AVG(oi.price) average_price
FROM gold.fact_order_items oi
LEFT JOIN gold.dim_products p ON oi.product_key = p.product_key
GROUP BY p.category_name
ORDER BY average_price DESC;

-- What is average freight in each category?
SELECT
	p.category_name,
	AVG(oi.freight_value) average_freight
FROM gold.fact_order_items oi
LEFT JOIN gold.dim_products p ON oi.product_key = p.product_key
GROUP BY p.category_name
ORDER BY average_freight DESC;

-- What is total revenue generated for each category?
SELECT
	dp.category_name,
	SUM(fp.payment_value) total_revenue
FROM gold.fact_payments fp
LEFT JOIN gold.fact_order_items oi ON fp.order_key = oi.order_key
LEFT JOIN gold.dim_products dp ON oi.product_key = dp.product_key
GROUP BY dp.category_name
ORDER BY total_revenue DESC;

-- Find total revenue is generated by each customer
SELECT
	dc.unique_id,
	SUM(fp.payment_value) total_revenue
FROM gold.fact_payments fp
LEFT JOIN gold.fact_orders fo ON fp.order_key = fo.order_key
LEFT JOIN gold.dim_customers dc ON fo.customer_key = dc.customer_key
GROUP BY dc.unique_id
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across state
SELECT
	dc.state,
	COUNT(oi.product_key) total_sold_items
FROM gold.fact_orders fo
LEFT JOIN gold.dim_customers dc ON fo.customer_key = dc.customer_key
LEFT JOIN gold.fact_order_items oi ON fo.order_key = oi.order_key
GROUP BY dc.state
ORDER BY total_sold_items DESC;

-- What is the distribution of sold items across city
SELECT
	dc.city,
	COUNT(oi.product_key) total_sold_items
FROM gold.fact_orders fo
LEFT JOIN gold.dim_customers dc ON fo.customer_key = dc.customer_key
LEFT JOIN gold.fact_order_items oi ON fo.order_key = oi.order_key
GROUP BY dc.city
ORDER BY total_sold_items DESC;
